FROM node:18-alpine

WORKDIR /app

# Copiar solo lo necesario
COPY package.json .
COPY tsconfig.json .

# Instalar dependencias
RUN npm install

# Copiar todo el código
COPY . .

# Compilar
RUN npm run build

# Puerto
EXPOSE 3000

# Comando simple
CMD ["node", "dist/index.js"]