FROM node:18-alpine

WORKDIR /app

# Copiar solo lo necesario
COPY package.json .
COPY tsconfig.json .

# Instalar dependencias
RUN npm install

# Copiar todo el código
COPY . .

# Compilar
RUN npm run build

# Puerto
EXPOSE 3000

# Comando que ejecuta migraciones ANTES de iniciar la aplicación
CMD ["sh", "-c", "npm run migration:run && node dist/index.js"]